# Generated by Django 3.1.7 on 2021-03-17 09:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorCourses', '0003_allcontents_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='your_choice',
            field=models.CharField(default=datetime.datetime(2021, 3, 17, 9, 51, 30, 428707, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
    ]
