# Generated by Django 3.1.7 on 2021-03-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorCourses', '0008_auto_20210317_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcontents',
            name='contentSummary',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
