# Generated by Django 3.1.7 on 2021-03-17 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorCourses', '0010_auto_20210317_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allcontents',
            name='document',
        ),
    ]
