# Generated by Django 3.1.7 on 2021-03-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorCourses', '0012_allcontents_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allcontents',
            name='document',
        ),
    ]
