# Generated by Django 3.1.7 on 2021-03-18 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorCourses', '0017_auto_20210317_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allcontents',
            options={'verbose_name_plural': 'all contents'},
        ),
    ]
