# Generated by Django 3.1.7 on 2021-04-03 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AuthorCourses', '0020_auto_20210318_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcontents',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
