# Generated by Django 3.1.7 on 2021-04-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorCourses', '0021_allcontents_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcontents',
            name='contentBody',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='allcontents',
            name='contentSummary',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
