# Generated by Django 3.1.7 on 2021-04-04 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthorCourses', '0022_auto_20210404_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcontents',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='AuthorCourses.category'),
        ),
        migrations.AlterField(
            model_name='allcontents',
            name='contentBody',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='allcontents',
            name='contentSummary',
            field=models.CharField(max_length=60),
        ),
    ]
